### ISSUE TITLE
Bug with the GMM parallel implementation

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.bio.gmm#3]
I found a bug in the GMM parallel implementation.

The number of statistics files that is written in the e-step (KMeans and M. Likelihood) are not the same amount of statistics read in the m-step.

Basically the check here
https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/tools/gmm.py#L40
must match with the check here
https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/tools/gmm.py#L124

AND

the check here:
https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/tools/gmm.py#L196
must match with the check here
https://github.com/bioidiap/bob.bio.gmm/blob/master/bob/bio/gmm/tools/gmm.py#L250

The crash happens only when you have few training files in the training set.
I'm opening the issue just to register. I will push the patch soon.
@siebenkopf , can I release a new version on pypi after this?

**Comment by siebenkopf** [comment]
Yes, please go ahead and fix this. However, it should not have an impact in most of the cases.
Anyways, a new version should be published  (given that the nose each tests pass).

**Comment by tiagofrepereira2012** [comment]
Fixed with the commit 64b3fc11694780f49d2465fad9dc68ede6f1735f
