### ISSUE TITLE
bob.bio.gmm should depend on bob.bio.face

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.bio.gmm#5]

**Comment by siebenkopf** [comment]
No. Do you find any reason for that? bob.bio.gmm can be run without any face algorithm, e.g., in combination with bob.bio.spear.

**Comment by 183amir** [comment]
Tiago was saying that this should depend on bob.bio.face :) but I see that this is not a bug now.

**Comment by tiagofrepereira2012** [comment]
Ops, sorry for the noise.
We just pull the bob.bio.face with bob.bio.gmm to have the bob.bio.face entry points (feature extractors, preprocessors, etc..)

**Comment by siebenkopf** [comment]
Yep, as documented here:
http://pythonhosted.org/bob.bio.base/installation.html

@183amir: Next time, when Tiago says that there is some bug, just let him open the issue, so that we can blame the right person from the beginning :-)
